### ISSUE TITLE
Disable CSS `max-line-length`, `at-rule-empty-line-before`, `comment-empty-line-before`, and `function-parentheses-space-inside`

### ISSUE THREAD

**Issue by iandunn** [WordPress/wordcamp.org#233]
For reference, you can look at this file, or run the linter on  `styles.css` in the `add/schedule-block` branch.

https://github.com/WordPress/wordcamp.org/blob/62d83c4/public_html/wp-content/mu-plugins/blocks/source/blocks/schedule/style.scss

### max-line-length

I can't think of a good way to shorten lines like:

```css
.edit-post-settings-sidebar__panel-block .components-panel__body .wordcamp-schedule__show-categories .components-base-control,
.edit-post-settings-sidebar__panel-block .components-panel__body .wordcamp-schedule__choose-specific-days .components-base-control,
.edit-post-settings-sidebar__panel-block .components-panel__body .wordcamp-schedule__choose-specific-tracks .components-base-control {
```

### at-rule-empty-line-before

I don't see any reason to add an empty line in a situation like this, and it would make it look awkward.

```css
.wordcamp-schedule__session-tracks {
	@include breakpoint-grid-layout {
		display: none;
	}
}
```

```css
.wordcamp-schedule__session-tracks {

	@include breakpoint-grid-layout {
		display: none;
	}
}
```

### comment-empty-line-before

I don't see any reason to add an empty line in a situation like this, and it would make it look awkward.

```css
&.is-end-time {
	/* End times are only useful on the Grid schedule. */
	display: none;

	@include breakpoint-grid-layout {
		display: flex;
	}
}
```

```css
&.is-end-time {

	/* End times are only useful on the Grid schedule. */
	display: none;

	@include breakpoint-grid-layout {
		display: flex;
	}
}
```

### function-parentheses-space-inside

I find it difficult to visually parse the values out when there isn't spacing around them. Having spacing there makes it consistent with PHP and JS standards for function calls.

```css
background-color: rgba( 251, 251, 252, 0.92 );
```

```css
background-color: rgba(251, 251, 252, 0.92);
```

What do y'all think?

**Comment by ryelle** [comment]
> I can't think of a good way to shorten lines like:
> 
> `.edit-post-settings-sidebar__panel-block .components-panel__body .wordcamp-schedule__show-categories .components-base-control,` …

Why does it need to be that long in the first place? Part of this rule is to find issues like this, do we need to be this specific? Are we trying to go against a gutenberg pattern here? Maybe we should double check with a designer before overriding too much.

But, if you really need to get this specific, you could break this up a bit by nesting rules:

```scss
.edit-post-settings-sidebar__panel-block .components-panel__body {
	.wordcamp-schedule__show-categories .components-base-control,
	.wordcamp-schedule__choose-specific-days .components-base-control,
	.wordcamp-schedule__choose-specific-tracks .components-base-control {
		margin-bottom: 0;
	}
}
```

> at-rule-empty-line-before

I think adding more space here makes things more readable, personally - it emphasizes that this isn't a regular CSS property.

> comment-empty-line-before

I don't really have a preference here, we can disable this if you want.

> function-parentheses-space-inside

Looks like this one's a core rule: "Do not pad parentheses with spaces." ([source](https://make.wordpress.org/core/handbook/best-practices/coding-standards/css/#values)) – I'd prefer to keep this, in that case.
