### ISSUE TITLE
Schedule: No space between hyphen and end time

### ISSUE THREAD

**Issue by nielslange** [WordPress/wordcamp.org#808]
**Describe the bug**

Currently, there's no space between the hyphen and the end time of a session.

**To reproduce**

1. Go to https://us.wordcamp.org/2022/schedule/.
2. Look at the session times and see that there's no space between the hyphen and the end time.
3. Please note that there's a space visible between the hyphen and the end time of the registration, as the default value had been overwritten with the following custom CSS:
```css
body.page-id-7 #wordcamp-schedule__session-5939 p::after {
    content: '7:30 am - 5:00 pm';
    font-size: 16px;
    margin: 1em 0 !important;
    line-height: 25px;
}
```

**Expected behavior**

There should always be a space between the start time, the hyphen, and the end time of a session.

**Screenshot**

<img width="1334" alt="Screenshot 2022-12-16 at 16 01 09" src="https://user-images.githubusercontent.com/3323310/208061999-6ea52d60-003e-4616-8a17-7a818335aaa7.png">

**Additional information**

The corresponding code, to display the session times, seems to be located here:

https://github.com/WordPress/wordcamp.org/blob/942eb3ad6e0aa8a51fce8652903af0664aeabc88/public_html/wp-content/mu-plugins/blocks/source/blocks/schedule/session.js#L113-L116

A potential fix could be to introduce the following code:

```js
const sessionTime = `{ date( timeFormat, startTime, timezone ) } - { date( timeFormat, endTime, timezone ) }`;
```

and then replacing

```jsx
<p>
    { date( timeFormat, startTime, timezone ) } -
    { date( timeFormat, endTime, timezone ) }
</p>
```

with

```jsx
<p>
    { sessionTime }
</p>
```
